services:
    backend:
        build:
            target: development
        working_dir: /app/backend
        volumes:
            - ./backend:/app/backend
        environment:
            - PORT=3101
            - NODE_ENV=development
            - ALLOWED_ORIGINS=http://localhost:8800
            - SERVICE_HOST=service
            - SERVICE_PORT=3102
        restart: on-failure
        command: ["bash", "-c", "yarn && yarn start:debug"]
        ports:
            - "3101:3101"
            - "9200:9229" # debug
        networks:
            - internal

    service:
        build:
            target: development
        working_dir: /app/service
        volumes:
            - ./service:/app/service
        environment:
            - PORT=3102
            - NODE_ENV=development
            - HOST=service
        restart: on-failure
        command: ["bash", "-c", "yarn && yarn start:debug"]
        ports:
            - "9201:9229" # debug
        networks:
            - internal

    frontend:
        build:
            target: development
        working_dir: /app/frontend
        volumes:
            - ./frontend:/app/frontend
        environment:
            - VITE_BASE_API_URL=http://localhost:3101
        command: ["bash", "-c", "yarn && yarn dev"]
        ports:
            - "8800:8800"

networks:
    internal:
        driver: bridge
